#! /bin/bash


i () {
    for P; do
        IFS=/ read u r t <<< "$P"
        test "$t" && git clone --depth 1 "https://github.com/$u/$r" -b "$b" "$u/$r-$t" \
                  || git clone --depth 1 "https://github.com/$u/$r" "$u/$r"

        test -f "$P/deps" &&
            while read d; do i "$d"; done < "$P/deps"
    done
}

u () { test $# = 0 && set */*; for d; do (cd "$d"; git pull); done; }
r () { rm -rf "$@"; }
l () { printf "%s\n" */*; }


shopt -s nullglob
mkdir -p ~/.shop ; cd ~/.shop

case "$1" in ( [iurl] ) "$@";;

             ( * ) _ () { printf '%b\n' "$@"; }
                   _ "Usage: shop [\e[3;32mCMD\e[m]"
                   _ ""
                   _ "\e[3;32mCMD\e[m is any of:"
                   _ ""
                   _ "  i [pkgs]   Install the given packages."
                   _ "             shop understands this format: \e[3;32m<user/repo>[/tag]\e[m."
                   _ "             If \e[3;32m/tag\e[m is given, the package will be installed"
                   _ "             as \e[3;32muser/repo-tag\e[m. Otherwise, as \e[3;32muser/repo\e[m."
                   _ "  u [pkgs]   Update all or the given packages."
                   _ "  r [pkgs]   Remove the given packages."
                   _ "  l          List installed packages."
                   exit 1;;
             esac
